"""initial migration with 6 core tables

Revision ID: 0300699e184b
Revises: 
Create Date: 2026-01-07 23:01:54.612243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0300699e184b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('POSTGRES', 'MYSQL', 'SQLSERVER', 'S3', 'AZURE_BLOB', 'GCS', 'BIGQUERY', 'SNOWFLAKE', 'API', name='connectortype'), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_connectors_type'), 'connectors', ['type'], unique=False)
    op.create_table('forecast_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('method', sa.Enum('ARIMA', 'ETS', 'PROPHET', name='forecastmethod'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='forecaststatus'), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('mae', sa.Integer(), nullable=True),
    sa.Column('rmse', sa.Integer(), nullable=True),
    sa.Column('mape', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_history_created_at'), 'forecast_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_history_status'), 'forecast_history', ['status'], unique=False)
    op.create_index(op.f('ix_forecast_history_tenant_id'), 'forecast_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_forecast_history_user_id'), 'forecast_history', ['user_id'], unique=False)
    op.create_table('usage_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('FORECAST_RUN', 'BATCH_FORECAST', 'DATA_UPLOAD', 'EXPORT', 'CONNECTOR_FETCH', name='usageaction'), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_stats_action'), 'usage_stats', ['action'], unique=False)
    op.create_index(op.f('ix_usage_stats_created_at'), 'usage_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_stats_tenant_id'), 'usage_stats', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_stats_user_id'), 'usage_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_stats_user_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_tenant_id'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_created_at'), table_name='usage_stats')
    op.drop_index(op.f('ix_usage_stats_action'), table_name='usage_stats')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_forecast_history_user_id'), table_name='forecast_history')
    op.drop_index(op.f('ix_forecast_history_tenant_id'), table_name='forecast_history')
    op.drop_index(op.f('ix_forecast_history_status'), table_name='forecast_history')
    op.drop_index(op.f('ix_forecast_history_created_at'), table_name='forecast_history')
    op.drop_table('forecast_history')
    op.drop_index(op.f('ix_connectors_type'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
