"""add_is_approved_to_users

Revision ID: 25dd1407ebe6
Revises: 0300699e184b
Create Date: 2026-01-08 17:22:48.276191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25dd1407ebe6'
down_revision: Union[str, None] = '0300699e184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_approved'), 'users', ['is_approved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_approved'), table_name='users')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
