"""add_user_groups_and_rls

Revision ID: b44a58c5806a
Revises: 25dd1407ebe6
Create Date: 2026-01-08 18:52:26.040036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44a58c5806a'
down_revision: Union[str, None] = '25dd1407ebe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rls_values', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_is_active'), 'user_groups', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_groups_tenant_id'), 'user_groups', ['tenant_id'], unique=False)
    op.create_table('user_group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_user_group_memberships_group_id'), 'user_group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_memberships_user_id'), 'user_group_memberships', ['user_id'], unique=False)
    op.create_table('connector_rls_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('rls_column', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_rls_configs_connector_id'), 'connector_rls_configs', ['connector_id'], unique=True)
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_super_admin'), 'users', ['is_super_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_super_admin'), table_name='users')
    op.drop_column('users', 'is_super_admin')
    op.drop_index(op.f('ix_connector_rls_configs_connector_id'), table_name='connector_rls_configs')
    op.drop_table('connector_rls_configs')
    op.drop_index(op.f('ix_user_group_memberships_user_id'), table_name='user_group_memberships')
    op.drop_index(op.f('ix_user_group_memberships_group_id'), table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    op.drop_index(op.f('ix_user_groups_tenant_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_is_active'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
