"""Add platform_admins table and remove is_super_admin from users

Revision ID: fe0abdbaa869
Revises: b44a58c5806a
Create Date: 2026-01-09 16:29:52.786505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0abdbaa869'
down_revision: Union[str, None] = 'b44a58c5806a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create platform_admins table
    op.create_table('platform_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)

    # Migrate existing super admins to platform_admins table
    op.execute("""
        INSERT INTO platform_admins (id, email, password_hash, full_name, is_active, last_login)
        SELECT id, email, password_hash, full_name, is_active, last_login
        FROM users WHERE is_super_admin = true
    """)

    # Remove is_super_admin column from users table
    op.drop_index('ix_users_is_super_admin', table_name='users')
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add is_super_admin column back to users table
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True, default=False))
    op.create_index('ix_users_is_super_admin', 'users', ['is_super_admin'])

    # Restore super admin flags from platform_admins
    op.execute("""
        UPDATE users SET is_super_admin = true
        WHERE email IN (SELECT email FROM platform_admins)
    """)

    # Drop platform_admins table
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
